@host=https://localhost:5001

GET {{host}}/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNjc0ZTU3My03MzBiLTQwZTMtOGU4Yi02NTU3ZGQzZThlZmUiLCJnaXZlbl9uYW1lIjoiVGhhaSIsImZhbWlseV9uYW1lIjoiVnUiLCJqdGkiOiJlZTgyZmU0Ni1mODE0LTQzN2QtYjNjNC0yZDhhYTY4ZTFiOWQiLCJleHAiOjE3MTExMDc4NjYsImlzcyI6Ik15UHJvamVjdCIsImF1ZCI6Ik15UHJvamVjdCJ9.JNQGYWIT1WmivkapWz5bFGZoIAUKILWLDCYlaG7sfnQ